services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow
      POSTGRES_DB: taskflow_auth
      POSTGRES_MULTIPLE_DATABASES: taskflow_tasks
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./infra/postgres-init-multiple-databases.sh:/docker-entrypoint-initdb.d/postgres-init-multiple-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskflow -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Simula SQS e SNS localmente
  localstack:
    build:
      context: ./infra
      dockerfile: localstack.Dockerfile
    environment:
      SERVICES: sqs,sns
    ports:
      - "4566:4566"

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: taskflow
      DB_PASS: taskflow
      DB_NAME: taskflow_auth
      JWT_SECRET: secret
      AWS_ENDPOINT: http://localstack:4566
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      SNS_TOPIC_ARN: arn:aws:sns:us-east-1:000000000000:user-events
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_started

  tasks-service:
    build: ./tasks-service
    ports:
      - "3002:3002"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: taskflow
      DB_PASS: taskflow
      DB_NAME: taskflow_tasks
      JWT_SECRET: secret
      AWS_ENDPOINT: http://localstack:4566
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      SQS_QUEUE_URL: http://localstack:4566/000000000000/user-events-tasks-queue
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_started

volumes:
  pg-data:
